apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policylabels
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: otus
  source:
    repoURL: https://github.com/iROFLMAOinMySoul/argocd-demo.git
    targetRevision: main
    path: "policies2"
  destination:
    server: https://kubernetes.default.svc
    namespace: policies
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
