apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
spec:
  destination:
    name: ''
    namespace: online-boutique
    server: https://kubernetes.default.svc
  source:
    path: manifests
    repoURL: https://github.com/iROFLMAOinMySoul/argocd-demo.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true