apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socks
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sock-shop
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
